INSERT INTO User (Name, Email, Password, Role, Status)
VALUES 
  ('John Doe', 'johndoe@example.com', 'password123', 'Customer', 1),
  ('Jane Smith', 'janesmith@example.com', 'password456', 'Expert', 1),
  ('Michael Johnson', 'michaeljohnson@example.com', 'password789', 'Admin', 1),
  ('Emily Davis', 'emilydavis@example.com', 'passwordabc', 'Customer', 1),
  ('Robert Wilson', 'robertwilson@example.com', 'passworddef', 'Expert', 1),
  ('Sophia Anderson', 'sophiaanderson@example.com', 'passwordghi', 'Customer', 1),
  ('Daniel Thomas', 'danielthomas@example.com', 'passwordjkl', 'Expert', 1),
  ('Olivia Clark', 'oliviaclark@example.com', 'passwordmno', 'Customer', 1),
  ('William Lee', 'williamlee@example.com', 'passwordpqr', 'Expert', 1),
  ('Ava Rodriguez', 'avarodriguez@example.com', 'passwordstu', 'Customer', 1);

INSERT INTO Categories (Name)
VALUES
('Science'),
('Mathematics'),
('History'),
('Literature'),
('Art'),
('Music'),
('Technology'),
('Business'),
('Language'),
('Sports');


INSERT INTO Course (Title, Thumbnail, Description, CategoryID)
VALUES
('Introduction to Biology', 'http://tny.im/uUA', 'A beginner course on the basics of biology', 1),
('Advanced Genetics', 'http://tny.im/uUB', 'An advanced course on genetics and DNA', 1),
('Calculus I', 'http://tny.im/uUC', 'An introductory course on calculus', 2),
('Linear Algebra', 'http://tny.im/uUD', 'A course on linear algebra and matrix theory', 2),
('World History I', 'thumbnail5.jpg', 'A survey of world history from ancient times to the Renaissance', 3),
('American Revolution', 'thumbnail6.jpg', 'A detailed study of the American Revolution and its impact', 3),
('Shakespearean Literature', 'thumbnail7.jpg', 'An introduction to the works of William Shakespeare', 4),
('Modern Poetry', 'thumbnail8.jpg', 'A survey of modern poetry from the 20th century to present day', 4),
('Painting Techniques', 'thumbnail9.jpg', 'A course on various painting techniques and styles', 5),
('Sculpture I', 'thumbnail10.jpg', 'An introduction to sculpture and three-dimensional art forms', 5),
('Music Theory I', 'thumbnail11.jpg', 'An introductory course on music theory and notation', 6),
('Jazz History', 'thumbnail12.jpg', 'A survey of jazz music and its history and evolution', 6),
('Introduction to Programming','thumbnail13.jpg','A beginner course on programming concepts and languages' ,7),
('Web Development','thumbnail14.jpg','A course on developing websites using HTML, CSS, and JavaScript' ,7),
('Accounting I','thumbnail15.jpg','An introductory course on accounting principles and practices' ,8),
('Marketing Strategies','thumbnail16.jpg','A course on developing effective marketing strategies for businesses' ,8),
('Spanish I','thumbnail17.jpg','An introductory course on the Spanish language and culture' ,9),
('French I','thumbnail18.jpg','An introductory course on the French language and culture' ,9),
('Basketball Fundamentals','thumbnail19.jpg','A beginner course on the fundamentals of basketball' ,10),
('Soccer Techniques','thumbnail20.jpg','A course on soccer techniques and strategies' ,10);

INSERT INTO Registration (CourseID, UserID, RegistrationDate, EndDate, Status)
VALUES
  (1, 1, '2023-07-12', '2023-08-12', 1),
  (2, 2, '2023-07-12', '2023-08-12', 1),
  (3, 3, '2023-07-12', '2023-08-12', 1),
  (4, 4, '2023-07-12', '2023-08-12', 1),
  (5, 5, '2023-07-12', '2023-08-12', 1),
  (6, 6, '2023-07-12', '2023-08-12', 1),
  (7, 7, '2023-07-12', '2023-08-12', 1),
  (8, 8, '2023-07-12', '2023-08-12', 1),
  (9, 9, '2023-07-12', '2023-08-12', 1),
  (10, 10, '2023-07-12', '2023-08-12', 1),
  (11, 1, '2023-07-12', '2023-08-12', 1),
  (12, 2, '2023-07-12', '2023-08-12', 1),
  (13, 3, '2023-07-12', '2023-08-12', 1),
  (14, 4, '2023-07-12', '2023-08-12', 1),
  (15, 5, '2023-07-12', '2023-08-12', 1),
  (16, 6, '2023-07-12', '2023-08-12', 1),
  (17, 7, '2023-07-12', '2023-08-12', 1),
  (18, 8, '2023-07-12', '2023-08-12', 1),
  (19, 9, '2023-07-12', '2023-08-12', 1),
  (20, 10, '2023-07-12', '2023-08-12', 1);
  
  INSERT INTO Test (CourseID, Title, Duration, Type)
VALUES
  (1, 'Quiz 1', 30, 'small'),
  (1, 'Midterm Exam', 90, 'midterm'),
  (1, 'Final Exam', 120, 'final'),
  (2, 'Quiz 1', 30, 'small'),
  (2, 'Midterm Exam', 90, 'midterm'),
  (2, 'Final Exam', 120, 'final'),
  (3, 'Quiz 1', 30, 'small'),
  (3, 'Midterm Exam', 90, 'midterm'),
  (3, 'Final Exam', 120, 'final'),
  (4, 'Quiz 1', 30, 'small'),
  (4, 'Midterm Exam', 90, 'midterm'),
  (4, 'Final Exam', 120, 'final'),
  (5, 'Quiz 1', 30, 'small'),
  (5, 'Midterm Exam', 90, 'midterm'),
  (5, 'Final Exam', 120, 'final'),
  (6, 'Quiz 1', 30, 'small'),
  (6, 'Midterm Exam', 90, 'midterm'),
  (6, 'Final Exam', 120, 'final'),
  (7, 'Quiz 1', 30, 'small'),
  (7, 'Midterm Exam', 90, 'midterm'),
  (7, 'Final Exam', 120, 'final'),
  (8, 'Quiz 1', 30, 'small'),
  (8, 'Midterm Exam', 90, 'midterm'),
  (8, 'Final Exam', 120, 'final'),
  (9, 'Quiz 1', 30, 'small'),
  (9, 'Midterm Exam', 90, 'midterm'),
  (9, 'Final Exam', 120, 'final'),
  (10, 'Quiz 1', 30, 'small'),
  (10, 'Midterm Exam', 90, 'midterm'),
  (10, 'Final Exam', 120, 'final'),
  (11, 'Quiz 1', 30, 'small'),
  (11, 'Midterm Exam', 90, 'midterm'),
  (11, 'Final Exam', 120, 'final'),
  (12, 'Quiz 1', 30, 'small'),
  (12, 'Midterm Exam', 90, 'midterm'),
  (12, 'Final Exam', 120, 'final'),
  (13, 'Quiz 1', 30, 'small'),
  (13, 'Midterm Exam', 90, 'midterm'),
  (13, 'Final Exam', 120, 'final'),
  (14, 'Quiz 1', 30, 'small'),
  (14, 'Midterm Exam', 90, 'midterm'),
  (14, 'Final Exam', 120, 'final'),
  (15, 'Quiz 1', 30, 'small'),
  (15, 'Midterm Exam', 90, 'midterm'),
  (15, 'Final Exam', 120, 'final'),
  (16, 'Quiz 1', 30, 'small'),
  (16, 'Midterm Exam', 90, 'midterm'),
  (16, 'Final Exam', 120, 'final'),
  (17, 'Quiz 1', 30, 'small'),
  (17, 'Midterm Exam', 90, 'midterm'),
  (17, 'Final Exam', 120, 'final'),
  (18, 'Quiz 1', 30, 'small'),
  (18, 'Midterm Exam', 90, 'midterm'),
  (18, 'Final Exam', 120, 'final'),
  (19, 'Quiz 1', 30, 'small'),
  (19, 'Midterm Exam', 90, 'midterm'),
  (19, 'Final Exam', 120, 'final'),
  (20, 'Quiz 1', 30, 'small'),
  (20, 'Midterm Exam', 90, 'midterm'),
  (20, 'Final Exam', 120, 'final');

INSERT INTO TestResult (TestID, UserID, Score, TestDate)
VALUES
  (1, 1, 85, '2023-07-15'), (2, 1, 75, '2023-07-20'), (3, 1, 95, '2023-07-25'),
  (1, 2, 90, '2023-07-16'), (2, 2, 80, '2023-07-21'), (3, 2, 92, '2023-07-26'),
  (1, 3, 78, '2023-07-17'), (2, 3, 88, '2023-07-22'), (3, 3, 82, '2023-07-27'),
  (1, 4, 92, '2023-07-18'), (2, 4, 85, '2023-07-23'), (3, 4, 88, '2023-07-28'),
  (1, 5, 70, '2023-07-19'), (2, 5, 78, '2023-07-24'), (3, 5, 90, '2023-07-29'),
  (1, 6, 85, '2023-07-15'), (2, 6, 90, '2023-07-21'), (3, 6, 95, '2023-07-25'),
  (1, 7, 75, '2023-07-16'), (2, 7, 80, '2023-07-22'), (3, 7, 92, '2023-07-26'),
  (1, 8, 78, '2023-07-17'), (2, 8, 88, '2023-07-23'), (3, 8, 82, '2023-07-27'),
  (1, 9, 92, '2023-07-18'), (2, 9, 85, '2023-07-24'), (3, 9, 88, '2023-07-28'),
  (1, 10, 70, '2023-07-19'), (2, 10, 78, '2023-07-25');
  
  INSERT INTO QuestionBank (TestID, QuestionText, A, B, C, D, CorrectAnswer)
VALUES
  (1, 'Which organelle is known as the powerhouse of the cell?', 'A. Mitochondria', 'B. Golgi Apparatus', 'C. Endoplasmic Reticulum', 'D. Nucleus', 'A'),
  (1, 'What is the basic unit of life?', 'A. Cell', 'B. Tissue', 'C. Organ', 'D. Organism', 'A'),
  (1, 'What is the process by which plants convert sunlight into energy?', 'A. Photosynthesis', 'B. Respiration', 'C. Digestion', 'D. Excretion', 'A'),
  (1, 'Which of the following is not a type of blood vessel?', 'A. Vein', 'B. Artery', 'C. Capillary', 'D. Alveoli', 'D'),
  (1, 'Which of the following is not a major macromolecule found in living organisms?', 'A. Carbohydrate', 'B. Protein', 'C. Nucleic Acid', 'D. Lipid', 'D'),
  (1, 'What is the study of how organisms interact with each other and their environment called?', 'A. Ecology', 'B. Genetics', 'C. Evolution', 'D. Microbiology', 'A'),
  (1, 'What is the largest organ in the human body?', 'A. Skin', 'B. Liver', 'C. Heart', 'D. Brain', 'A'),
  (1, 'What is the scientific name for the process of cell division?', 'A. Mitosis', 'B. Meiosis', 'C. Replication', 'D. Transcription', 'A'),
  (1, 'Which of the following is not a type of RNA?', 'A. Messenger RNA (mRNA)', 'B. Transfer RNA (tRNA)', 'C. Ribosomal RNA (rRNA)', 'D. Deoxyribonucleic Acid (DNA)', 'D'),
  (1, 'What is the largest organ in the plant body?', 'A. Leaf', 'B. Stem', 'C. Root', 'D. Flower', 'B'),
  -- midterm 
  (2, 'Which organelle is known as the powerhouse of the cell?', 'A. Mitochondria', 'B. Golgi Apparatus', 'C. Endoplasmic Reticulum', 'D. Nucleus', 'A'),
  (2, 'What is the basic unit of life?', 'A. Cell', 'B. Tissue', 'C. Organ', 'D. Organism', 'A'),
  (2, 'What is the process by which plants convert sunlight into energy?', 'A. Photosynthesis', 'B. Respiration', 'C. Digestion', 'D. Excretion', 'A'),
  (2, 'Which of the following is not a type of blood vessel?', 'A. Vein', 'B. Artery', 'C. Capillary', 'D. Alveoli', 'D'),
  (2, 'Which of the following is not a major macromolecule found in living organisms?', 'A. Carbohydrate', 'B. Protein', 'C. Nucleic Acid', 'D. Lipid', 'D'),
  (2, 'What is the study of how organisms interact with each other and their environment called?', 'A. Ecology', 'B. Genetics', 'C. Evolution', 'D. Microbiology', 'A'),
  (2, 'What is the largest organ in the human body?', 'A. Skin', 'B. Liver', 'C. Heart', 'D. Brain', 'A'),
  (2, 'What is the scientific name for the process of cell division?', 'A. Mitosis', 'B. Meiosis', 'C. Replication', 'D. Transcription', 'A'),
  (2, 'Which of the following is not a type of RNA?', 'A. Messenger RNA (mRNA)', 'B. Transfer RNA (tRNA)', 'C. Ribosomal RNA (rRNA)', 'D. Deoxyribonucleic Acid (DNA)', 'D'),
  (2, 'What is the largest organ in the plant body?', 'A. Leaf', 'B. Stem', 'C. Root', 'D. Flower', 'B'),
  -- final
  (3, 'Which organelle is known as the powerhouse of the cell?', 'A. Mitochondria', 'B. Golgi Apparatus', 'C. Endoplasmic Reticulum', 'D. Nucleus', 'A'),
  (3, 'What is the basic unit of life?', 'A. Cell', 'B. Tissue', 'C. Organ', 'D. Organism', 'A'),
  (3, 'What is the process by which plants convert sunlight into energy?', 'A. Photosynthesis', 'B. Respiration', 'C. Digestion', 'D. Excretion', 'A'),
  (3, 'Which of the following is not a type of blood vessel?', 'A. Vein', 'B. Artery', 'C. Capillary', 'D. Alveoli', 'D'),
  (3, 'Which of the following is not a major macromolecule found in living organisms?', 'A. Carbohydrate', 'B. Protein', 'C. Nucleic Acid', 'D. Lipid', 'D'),
  (3, 'What is the study of how organisms interact with each other and their environment called?', 'A. Ecology', 'B. Genetics', 'C. Evolution', 'D. Microbiology', 'A'),
  (3, 'What is the largest organ in the human body?', 'A. Skin', 'B. Liver', 'C. Heart', 'D. Brain', 'A'),
  (3, 'What is the scientific name for the process of cell division?', 'A. Mitosis', 'B. Meiosis', 'C. Replication', 'D. Transcription', 'A'),
  (3, 'Which of the following is not a type of RNA?', 'A. Messenger RNA (mRNA)', 'B. Transfer RNA (tRNA)', 'C. Ribosomal RNA (rRNA)', 'D. Deoxyribonucleic Acid (DNA)', 'D'),
  (3, 'What is the largest organ in the plant body?', 'A. Leaf', 'B. Stem', 'C. Root', 'D. Flower', 'B'),
  -- quiz for TestID: 2 (Advanced Genetics)
  (4, 'What is the term for an alternative form of a gene?', 'A. Allele', 'B. Chromosome', 'C. Homozygote', 'D. Phenotype', 'A'),
  (4, 'Which process results in the production of gametes?', 'A. Meiosis', 'B. Mitosis', 'C. Replication', 'D. Transcription', 'A'),
  (4, 'What is the name of the DNA structure that forms when two DNA strands twist around each other?', 'A. Double helix', 'B. Chromatin', 'C. Nucleosome', 'D. Centromere', 'A'),
  (4, 'Which of the following is a genetic disorder caused by the presence of an extra chromosome 21?', 'A. Down syndrome', 'B. Turner syndrome', 'C. Klinefelter syndrome', 'D. Cystic fibrosis', 'A'),
  (4, 'What is the process by which genetic information is copied from DNA to RNA?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (4, 'Which scientist is credited with discovering the laws of inheritance?', 'A. Gregor Mendel', 'B. Charles Darwin', 'C. Rosalind Franklin', 'D. James Watson', 'A'),
  (4, 'What is the term for the specific location of a gene on a chromosome?', 'A. Locus', 'B. Phenotype', 'C. Genotype', 'D. Allele', 'A'),
  (4, 'Which of the following genetic disorders is characterized by the inability to break down phenylalanine?', 'A. Phenylketonuria (PKU)', 'B. Huntington\'s disease', 'C. Hemophilia', 'D. Muscular dystrophy', 'A'),
  (4, 'What is the name of the process by which RNA is synthesized from a DNA template?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (4, 'What is the term for an organism that has two different alleles for a particular gene?', 'A. Heterozygote', 'B. Homozygote', 'C. Dominant', 'D. Recessive', 'A'),
  -- midterm
  (5, 'What is the term for an alternative form of a gene?', 'A. Allele', 'B. Chromosome', 'C. Homozygote', 'D. Phenotype', 'A'),
  (5, 'Which process results in the production of gametes?', 'A. Meiosis', 'B. Mitosis', 'C. Replication', 'D. Transcription', 'A'),
  (5, 'What is the name of the DNA structure that forms when two DNA strands twist around each other?', 'A. Double helix', 'B. Chromatin', 'C. Nucleosome', 'D. Centromere', 'A'),
  (5, 'Which of the following is a genetic disorder caused by the presence of an extra chromosome 21?', 'A. Down syndrome', 'B. Turner syndrome', 'C. Klinefelter syndrome', 'D. Cystic fibrosis', 'A'),
  (5, 'What is the process by which genetic information is copied from DNA to RNA?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (5, 'Which scientist is credited with discovering the laws of inheritance?', 'A. Gregor Mendel', 'B. Charles Darwin', 'C. Rosalind Franklin', 'D. James Watson', 'A'),
  (5, 'What is the term for the specific location of a gene on a chromosome?', 'A. Locus', 'B. Phenotype', 'C. Genotype', 'D. Allele', 'A'),
  (5, 'Which of the following genetic disorders is characterized by the inability to break down phenylalanine?', 'A. Phenylketonuria (PKU)', 'B. Huntington\'s disease', 'C. Hemophilia', 'D. Muscular dystrophy', 'A'),
  (5, 'What is the name of the process by which RNA is synthesized from a DNA template?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (5, 'What is the term for an organism that has two different alleles for a particular gene?', 'A. Heterozygote', 'B. Homozygote', 'C. Dominant', 'D. Recessive', 'A'),
-- final
(6, 'What is the term for an alternative form of a gene?', 'A. Allele', 'B. Chromosome', 'C. Homozygote', 'D. Phenotype', 'A'),
  (6, 'Which process results in the production of gametes?', 'A. Meiosis', 'B. Mitosis', 'C. Replication', 'D. Transcription', 'A'),
  (6, 'What is the name of the DNA structure that forms when two DNA strands twist around each other?', 'A. Double helix', 'B. Chromatin', 'C. Nucleosome', 'D. Centromere', 'A'),
  (6, 'Which of the following is a genetic disorder caused by the presence of an extra chromosome 21?', 'A. Down syndrome', 'B. Turner syndrome', 'C. Klinefelter syndrome', 'D. Cystic fibrosis', 'A'),
  (6, 'What is the process by which genetic information is copied from DNA to RNA?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (6, 'Which scientist is credited with discovering the laws of inheritance?', 'A. Gregor Mendel', 'B. Charles Darwin', 'C. Rosalind Franklin', 'D. James Watson', 'A'),
  (6, 'What is the term for the specific location of a gene on a chromosome?', 'A. Locus', 'B. Phenotype', 'C. Genotype', 'D. Allele', 'A'),
  (6, 'Which of the following genetic disorders is characterized by the inability to break down phenylalanine?', 'A. Phenylketonuria (PKU)', 'B. Huntington\'s disease', 'C. Hemophilia', 'D. Muscular dystrophy', 'A'),
  (6, 'What is the name of the process by which RNA is synthesized from a DNA template?', 'A. Transcription', 'B. Translation', 'C. Replication', 'D. Mutation', 'A'),
  (6, 'What is the term for an organism that has two different alleles for a particular gene?', 'A. Heterozygote', 'B. Homozygote', 'C. Dominant', 'D. Recessive', 'A'),
  -- quiz for TestID: 3 (Calculus I)
  (7, 'What is the derivative of a constant?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'A'),
  (7, 'What is the integral of x^n?', 'A. (x^(n+1))/(n+1)', 'B. (n+1)/x^(n+1)', 'C. (1/n)x^(n-1)', 'D. (1/n+1)x^(n+1)', 'A'),
  (7, 'What is the limit of (sin(x))/x as x approaches 0?', 'A. 1', 'B. 0', 'C. -1', 'D. Undefined', 'A'),
  (7, 'Which rule states that the derivative of a constant times a function is equal to the constant times the derivative of the function?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Product Rule', 'D'),
  (7, 'What is the derivative of e^x?', 'A. e^x', 'B. e^(x-1)', 'C. 1/e^x', 'D. Undefined', 'A'),
  (7, 'What is the integral of 1/x?', 'A. ln|x|', 'B. x^2/2', 'C. e^x', 'D. Undefined', 'A'),
  (7, 'Which rule states that the derivative of a sum of functions is equal to the sum of their derivatives?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Sum Rule', 'D'),
  (7, 'What is the derivative of sin(x)?', 'A. cos(x)', 'B. -sin(x)', 'C. tan(x)', 'D. Undefined', 'A'),
  (7, 'What is the integral of cos(x)?', 'A. sin(x)', 'B. -cos(x)', 'C. tan(x)', 'D. Undefined', 'B'),
  (7, 'What is the limit of (1-cos(x))/x as x approaches 0?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'B'),
	-- midterm
  (8, 'What is the derivative of a constant?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'A'),
  (8, 'What is the integral of x^n?', 'A. (x^(n+1))/(n+1)', 'B. (n+1)/x^(n+1)', 'C. (1/n)x^(n-1)', 'D. (1/n+1)x^(n+1)', 'A'),
  (8, 'What is the limit of (sin(x))/x as x approaches 0?', 'A. 1', 'B. 0', 'C. -1', 'D. Undefined', 'A'),
  (8, 'Which rule states that the derivative of a constant times a function is equal to the constant times the derivative of the function?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Product Rule', 'D'),
  (8, 'What is the derivative of e^x?', 'A. e^x', 'B. e^(x-1)', 'C. 1/e^x', 'D. Undefined', 'A'),
  (8, 'What is the integral of 1/x?', 'A. ln|x|', 'B. x^2/2', 'C. e^x', 'D. Undefined', 'A'),
  (8, 'Which rule states that the derivative of a sum of functions is equal to the sum of their derivatives?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Sum Rule', 'D'),
  (8, 'What is the derivative of sin(x)?', 'A. cos(x)', 'B. -sin(x)', 'C. tan(x)', 'D. Undefined', 'A'),
  (8, 'What is the integral of cos(x)?', 'A. sin(x)', 'B. -cos(x)', 'C. tan(x)', 'D. Undefined', 'B'),
  (8, 'What is the limit of (1-cos(x))/x as x approaches 0?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'B'),
   -- final
   (9, 'What is the derivative of a constant?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'A'),
  (9, 'What is the integral of x^n?', 'A. (x^(n+1))/(n+1)', 'B. (n+1)/x^(n+1)', 'C. (1/n)x^(n-1)', 'D. (1/n+1)x^(n+1)', 'A'),
  (9, 'What is the limit of (sin(x))/x as x approaches 0?', 'A. 1', 'B. 0', 'C. -1', 'D. Undefined', 'A'),
  (9, 'Which rule states that the derivative of a constant times a function is equal to the constant times the derivative of the function?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Product Rule', 'D'),
  (9, 'What is the derivative of e^x?', 'A. e^x', 'B. e^(x-1)', 'C. 1/e^x', 'D. Undefined', 'A'),
  (9, 'What is the integral of 1/x?', 'A. ln|x|', 'B. x^2/2', 'C. e^x', 'D. Undefined', 'A'),
  (9, 'Which rule states that the derivative of a sum of functions is equal to the sum of their derivatives?', 'A. Constant Rule', 'B. Power Rule', 'C. Chain Rule', 'D. Sum Rule', 'D'),
  (9, 'What is the derivative of sin(x)?', 'A. cos(x)', 'B. -sin(x)', 'C. tan(x)', 'D. Undefined', 'A'),
  (9, 'What is the integral of cos(x)?', 'A. sin(x)', 'B. -cos(x)', 'C. tan(x)', 'D. Undefined', 'B'),
  (9, 'What is the limit of (1-cos(x))/x as x approaches 0?', 'A. 0', 'B. 1', 'C. -1', 'D. Undefined', 'B'),
  -- quiz for TestID: 4 (Linear Algebra)
(10, 'What is the determinant of a 2x2 matrix?', 'A. ad - bc', 'B. a + b + c + d', 'C. a - b - c - d', 'D. a^2 + b^2 + c^2 + d^2', 'A'),
(10, 'Which of the following operations is NOT allowed on matrices?', 'A. Matrix addition', 'B. Matrix multiplication', 'C. Matrix division', 'D. Scalar multiplication', 'C'),
(10, 'What is the rank of a matrix?', 'A. The number of rows in the matrix', 'B. The number of columns in the matrix', 'C. The sum of all elements in the matrix', 'D. The maximum number of linearly independent rows or columns in the matrix', 'D'),
(10, 'What is an eigenvector?', 'A. A vector with all elements equal to 1', 'B. A vector that is perpendicular to all other vectors', 'C. A vector that does not change direction when multiplied by a matrix', 'D. A vector with the maximum length in a matrix', 'C'),
(10, 'What is the dot product of two vectors?', 'A. The sum of the products of their corresponding elements', 'B. The difference between their magnitudes', 'C. The product of their magnitudes', 'D. The sum of their magnitudes', 'A'),
(10, 'What is the inverse of a matrix?', 'A. The matrix obtained by swapping rows and columns', 'B. The matrix obtained by dividing each element by the determinant', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(10, 'What is a singular matrix?', 'A. A matrix with only one non-zero element', 'B. A matrix with all elements equal to zero', 'C. A matrix with equal number of rows and columns', 'D. A matrix that does not have an inverse', 'D'),
(10, 'What is the transpose of a matrix?', 'A. The matrix obtained by dividing each element by the determinant', 'B. The matrix obtained by swapping rows and columns', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(10, 'What is the span of a set of vectors?', 'A. The sum of all elements in the vectors', 'B. The number of linearly independent vectors in the set', 'C. The maximum number of vectors that can be multiplied together', 'D. The set of all possible linear combinations of the vectors', 'D'),
(10, 'What is the eigenvalue of a matrix?', 'A. The sum of all elements in the matrix', 'B. The difference between the largest and smallest elements in the matrix', 'C. The maximum number of linearly independent rows or columns in the matrix', 'D. A scalar value that satisfies the equation Av = λv, where A is the matrix, v is the eigenvector, and λ is the eigenvalue', 'D'),
 -- midterm
 (11, 'What is the determinant of a 2x2 matrix?', 'A. ad - bc', 'B. a + b + c + d', 'C. a - b - c - d', 'D. a^2 + b^2 + c^2 + d^2', 'A'),
(11, 'Which of the following operations is NOT allowed on matrices?', 'A. Matrix addition', 'B. Matrix multiplication', 'C. Matrix division', 'D. Scalar multiplication', 'C'),
(11, 'What is the rank of a matrix?', 'A. The number of rows in the matrix', 'B. The number of columns in the matrix', 'C. The sum of all elements in the matrix', 'D. The maximum number of linearly independent rows or columns in the matrix', 'D'),
(11, 'What is an eigenvector?', 'A. A vector with all elements equal to 1', 'B. A vector that is perpendicular to all other vectors', 'C. A vector that does not change direction when multiplied by a matrix', 'D. A vector with the maximum length in a matrix', 'C'),
(11, 'What is the dot product of two vectors?', 'A. The sum of the products of their corresponding elements', 'B. The difference between their magnitudes', 'C. The product of their magnitudes', 'D. The sum of their magnitudes', 'A'),
(11, 'What is the inverse of a matrix?', 'A. The matrix obtained by swapping rows and columns', 'B. The matrix obtained by dividing each element by the determinant', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(11, 'What is a singular matrix?', 'A. A matrix with only one non-zero element', 'B. A matrix with all elements equal to zero', 'C. A matrix with equal number of rows and columns', 'D. A matrix that does not have an inverse', 'D'),
(11, 'What is the transpose of a matrix?', 'A. The matrix obtained by dividing each element by the determinant', 'B. The matrix obtained by swapping rows and columns', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(11, 'What is the span of a set of vectors?', 'A. The sum of all elements in the vectors', 'B. The number of linearly independent vectors in the set', 'C. The maximum number of vectors that can be multiplied together', 'D. The set of all possible linear combinations of the vectors', 'D'),
(11, 'What is the eigenvalue of a matrix?', 'A. The sum of all elements in the matrix', 'B. The difference between the largest and smallest elements in the matrix', 'C. The maximum number of linearly independent rows or columns in the matrix', 'D. A scalar value that satisfies the equation Av = λv, where A is the matrix, v is the eigenvector, and λ is the eigenvalue', 'D'),
-- final
(12, 'What is the determinant of a 2x2 matrix?', 'A. ad - bc', 'B. a + b + c + d', 'C. a - b - c - d', 'D. a^2 + b^2 + c^2 + d^2', 'A'),
(12, 'Which of the following operations is NOT allowed on matrices?', 'A. Matrix addition', 'B. Matrix multiplication', 'C. Matrix division', 'D. Scalar multiplication', 'C'),
(12, 'What is the rank of a matrix?', 'A. The number of rows in the matrix', 'B. The number of columns in the matrix', 'C. The sum of all elements in the matrix', 'D. The maximum number of linearly independent rows or columns in the matrix', 'D'),
(12, 'What is an eigenvector?', 'A. A vector with all elements equal to 1', 'B. A vector that is perpendicular to all other vectors', 'C. A vector that does not change direction when multiplied by a matrix', 'D. A vector with the maximum length in a matrix', 'C'),
(12, 'What is the dot product of two vectors?', 'A. The sum of the products of their corresponding elements', 'B. The difference between their magnitudes', 'C. The product of their magnitudes', 'D. The sum of their magnitudes', 'A'),
(12, 'What is the inverse of a matrix?', 'A. The matrix obtained by swapping rows and columns', 'B. The matrix obtained by dividing each element by the determinant', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(12, 'What is a singular matrix?', 'A. A matrix with only one non-zero element', 'B. A matrix with all elements equal to zero', 'C. A matrix with equal number of rows and columns', 'D. A matrix that does not have an inverse', 'D'),
(12, 'What is the transpose of a matrix?', 'A. The matrix obtained by dividing each element by the determinant', 'B. The matrix obtained by swapping rows and columns', 'C. The matrix obtained by changing the sign of each element', 'D. The matrix obtained by multiplying each element by its cofactor', 'B'),
(12, 'What is the span of a set of vectors?', 'A. The sum of all elements in the vectors', 'B. The number of linearly independent vectors in the set', 'C. The maximum number of vectors that can be multiplied together', 'D. The set of all possible linear combinations of the vectors', 'D'),
(12, 'What is the eigenvalue of a matrix?', 'A. The sum of all elements in the matrix', 'B. The difference between the largest and smallest elements in the matrix', 'C. The maximum number of linearly independent rows or columns in the matrix', 'D. A scalar value that satisfies the equation Av = λv, where A is the matrix, v is the eigenvector, and λ is the eigenvalue', 'D'),
-- quiz for TestID: 5 (World History I)
(13, 'Who was the first emperor of unified China?', 'A. Qin Shi Huang', 'B. Alexander the Great', 'C. Julius Caesar', 'D. Ashoka the Great', 'A'),
(13, 'Which civilization built the Great Pyramids of Giza?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(13, 'What event marked the beginning of the Middle Ages?', 'A. The fall of the Roman Empire', 'B. The French Revolution', 'C. The Renaissance', 'D. The Protestant Reformation', 'A'),
(13, 'Who was the first European explorer to reach India by sea?', 'A. Vasco da Gama', 'B. Christopher Columbus', 'C. Ferdinand Magellan', 'D. James Cook', 'A'),
(13, 'Which empire was responsible for the construction of the Hagia Sophia?', 'A. Byzantine Empire', 'B. Ottoman Empire', 'C. Persian Empire', 'D. Mongol Empire', 'A'),
(13, 'Who was the last pharaoh of ancient Egypt?', 'A. Cleopatra', 'B. Ramses II', 'C. Tutankhamun', 'D. Nefertiti', 'A'),
(13, 'What was the primary religion of the Byzantine Empire?', 'A. Christianity', 'B. Islam', 'C. Judaism', 'D. Zoroastrianism', 'A'),
(13, 'Who was the founder of Buddhism?', 'A. Siddhartha Gautama', 'B. Confucius', 'C. Laozi', 'D. Ashoka the Great', 'A'),
(13, 'Which city was the capital of the Aztec Empire?', 'A. Tenochtitlan', 'B. Machu Picchu', 'C. Cusco', 'D. Tikal', 'A'),
(13, 'Which European country was the dominant naval power during the Age of Exploration?', 'A. Spain', 'B. Portugal', 'C. England', 'D. France', 'A'),
-- midterm
(14, 'Who was the first emperor of unified China?', 'A. Qin Shi Huang', 'B. Alexander the Great', 'C. Julius Caesar', 'D. Ashoka the Great', 'A'),
(14, 'Which civilization built the Great Pyramids of Giza?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(14, 'What event marked the beginning of the Middle Ages?', 'A. The fall of the Roman Empire', 'B. The French Revolution', 'C. The Renaissance', 'D. The Protestant Reformation', 'A'),
(14, 'Who was the first European explorer to reach India by sea?', 'A. Vasco da Gama', 'B. Christopher Columbus', 'C. Ferdinand Magellan', 'D. James Cook', 'A'),
(14, 'Which empire was responsible for the construction of the Hagia Sophia?', 'A. Byzantine Empire', 'B. Ottoman Empire', 'C. Persian Empire', 'D. Mongol Empire', 'A'),
(14, 'Who was the last pharaoh of ancient Egypt?', 'A. Cleopatra', 'B. Ramses II', 'C. Tutankhamun', 'D. Nefertiti', 'A'),
(14, 'What was the primary religion of the Byzantine Empire?', 'A. Christianity', 'B. Islam', 'C. Judaism', 'D. Zoroastrianism', 'A'),
(14, 'Who was the founder of Buddhism?', 'A. Siddhartha Gautama', 'B. Confucius', 'C. Laozi', 'D. Ashoka the Great', 'A'),
(14, 'Which city was the capital of the Aztec Empire?', 'A. Tenochtitlan', 'B. Machu Picchu', 'C. Cusco', 'D. Tikal', 'A'),
(14, 'Which European country was the dominant naval power during the Age of Exploration?', 'A. Spain', 'B. Portugal', 'C. England', 'D. France', 'A'),
-- final
(15, 'Who was the first emperor of unified China?', 'A. Qin Shi Huang', 'B. Alexander the Great', 'C. Julius Caesar', 'D. Ashoka the Great', 'A'),
(15, 'Which civilization built the Great Pyramids of Giza?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(15, 'What event marked the beginning of the Middle Ages?', 'A. The fall of the Roman Empire', 'B. The French Revolution', 'C. The Renaissance', 'D. The Protestant Reformation', 'A'),
(15, 'Who was the first European explorer to reach India by sea?', 'A. Vasco da Gama', 'B. Christopher Columbus', 'C. Ferdinand Magellan', 'D. James Cook', 'A'),
(15, 'Which empire was responsible for the construction of the Hagia Sophia?', 'A. Byzantine Empire', 'B. Ottoman Empire', 'C. Persian Empire', 'D. Mongol Empire', 'A'),
(15, 'Who was the last pharaoh of ancient Egypt?', 'A. Cleopatra', 'B. Ramses II', 'C. Tutankhamun', 'D. Nefertiti', 'A'),
(15, 'What was the primary religion of the Byzantine Empire?', 'A. Christianity', 'B. Islam', 'C. Judaism', 'D. Zoroastrianism', 'A'),
(15, 'Who was the founder of Buddhism?', 'A. Siddhartha Gautama', 'B. Confucius', 'C. Laozi', 'D. Ashoka the Great', 'A'),
(15, 'Which city was the capital of the Aztec Empire?', 'A. Tenochtitlan', 'B. Machu Picchu', 'C. Cusco', 'D. Tikal', 'A'),
(15, 'Which European country was the dominant naval power during the Age of Exploration?', 'A. Spain', 'B. Portugal', 'C. England', 'D. France', 'A'),
-- quiz for TestID: 6 (American Revolution)
(16, 'Which event marked the beginning of the American Revolution?', 'A. The Boston Tea Party', 'B. The signing of the Declaration of Independence', 'C. The Battle of Lexington and Concord', 'D. The Stamp Act', 'C'),
(16, 'Who was the primary author of the Declaration of Independence?', 'A. Thomas Jefferson', 'B. George Washington', 'C. Benjamin Franklin', 'D. John Adams', 'A'),
(16, 'Which battle is considered the turning point of the American Revolution?', 'A. Battle of Saratoga', 'B. Battle of Yorktown', 'C. Battle of Bunker Hill', 'D. Battle of Trenton', 'A'),
(16, 'What was the name of the treaty that officially ended the American Revolution?', 'A. Treaty of Paris', 'B. Treaty of Versailles', 'C. Treaty of Ghent', 'D. Treaty of Alliance', 'A'),
(16, 'Who was the commander-in-chief of the Continental Army?', 'A. George Washington', 'B. Thomas Jefferson', 'C. John Adams', 'D. Alexander Hamilton', 'A'),
(16, 'Which country provided significant military and financial support to the American colonies during the Revolution?', 'A. France', 'B. Spain', 'C. England', 'D. Netherlands', 'A'),
(16, 'Which event led to the Boston Massacre?', 'A. The Townshend Acts', 'B. The Intolerable Acts', 'C. The Tea Act', 'D. The Quartering Act', 'A'),
(16, 'Who famously said, "Give me liberty or give me death!"?', 'A. Patrick Henry', 'B. Thomas Paine', 'C. John Hancock', 'D. Samuel Adams', 'A'),
(16, 'What was the name of the pamphlet written by Thomas Paine that inspired American colonists to support independence?', 'A. Common Sense', 'B. The Federalist Papers', 'C. The Wealth of Nations', 'D. Poor Richard\'s Almanack', 'A'),
(16, 'Which state was the first to ratify the United States Constitution?', 'A. Delaware', 'B. New York', 'C. Pennsylvania', 'D. Massachusetts', 'A'),
-- midterm 
(17, 'Which event marked the beginning of the American Revolution?', 'A. The Boston Tea Party', 'B. The signing of the Declaration of Independence', 'C. The Battle of Lexington and Concord', 'D. The Stamp Act', 'C'),
(17, 'Who was the primary author of the Declaration of Independence?', 'A. Thomas Jefferson', 'B. George Washington', 'C. Benjamin Franklin', 'D. John Adams', 'A'),
(17, 'Which battle is considered the turning point of the American Revolution?', 'A. Battle of Saratoga', 'B. Battle of Yorktown', 'C. Battle of Bunker Hill', 'D. Battle of Trenton', 'A'),
(17, 'What was the name of the treaty that officially ended the American Revolution?', 'A. Treaty of Paris', 'B. Treaty of Versailles', 'C. Treaty of Ghent', 'D. Treaty of Alliance', 'A'),
(17, 'Who was the commander-in-chief of the Continental Army?', 'A. George Washington', 'B. Thomas Jefferson', 'C. John Adams', 'D. Alexander Hamilton', 'A'),
(17, 'Which country provided significant military and financial support to the American colonies during the Revolution?', 'A. France', 'B. Spain', 'C. England', 'D. Netherlands', 'A'),
(17, 'Which event led to the Boston Massacre?', 'A. The Townshend Acts', 'B. The Intolerable Acts', 'C. The Tea Act', 'D. The Quartering Act', 'A'),
(17, 'Who famously said, "Give me liberty or give me death!"?', 'A. Patrick Henry', 'B. Thomas Paine', 'C. John Hancock', 'D. Samuel Adams', 'A'),
(17, 'What was the name of the pamphlet written by Thomas Paine that inspired American colonists to support independence?', 'A. Common Sense', 'B. The Federalist Papers', 'C. The Wealth of Nations', 'D. Poor Richard\'s Almanack', 'A'),
(17, 'Which state was the first to ratify the United States Constitution?', 'A. Delaware', 'B. New York', 'C. Pennsylvania', 'D. Massachusetts', 'A'),
-- final
(18, 'Which event marked the beginning of the American Revolution?', 'A. The Boston Tea Party', 'B. The signing of the Declaration of Independence', 'C. The Battle of Lexington and Concord', 'D. The Stamp Act', 'C'),
(18, 'Who was the primary author of the Declaration of Independence?', 'A. Thomas Jefferson', 'B. George Washington', 'C. Benjamin Franklin', 'D. John Adams', 'A'),
(18, 'Which battle is considered the turning point of the American Revolution?', 'A. Battle of Saratoga', 'B. Battle of Yorktown', 'C. Battle of Bunker Hill', 'D. Battle of Trenton', 'A'),
(18, 'What was the name of the treaty that officially ended the American Revolution?', 'A. Treaty of Paris', 'B. Treaty of Versailles', 'C. Treaty of Ghent', 'D. Treaty of Alliance', 'A'),
(18, 'Who was the commander-in-chief of the Continental Army?', 'A. George Washington', 'B. Thomas Jefferson', 'C. John Adams', 'D. Alexander Hamilton', 'A'),
(18, 'Which country provided significant military and financial support to the American colonies during the Revolution?', 'A. France', 'B. Spain', 'C. England', 'D. Netherlands', 'A'),
(18, 'Which event led to the Boston Massacre?', 'A. The Townshend Acts', 'B. The Intolerable Acts', 'C. The Tea Act', 'D. The Quartering Act', 'A'),
(18, 'Who famously said, "Give me liberty or give me death!"?', 'A. Patrick Henry', 'B. Thomas Paine', 'C. John Hancock', 'D. Samuel Adams', 'A'),
(18, 'What was the name of the pamphlet written by Thomas Paine that inspired American colonists to support independence?', 'A. Common Sense', 'B. The Federalist Papers', 'C. The Wealth of Nations', 'D. Poor Richard\'s Almanack', 'A'),
(18, 'Which state was the first to ratify the United States Constitution?', 'A. Delaware', 'B. New York', 'C. Pennsylvania', 'D. Massachusetts', 'A'),
-- quiz for TestID: 7 (Shakespearean Literature)
(19, 'Who is the author of the play "Romeo and Juliet"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(19, 'In which city is the play "Macbeth" primarily set?', 'A. Inverness', 'B. Rome', 'C. Athens', 'D. Verona', 'A'),
(19, 'What is the name of the character known for his famous soliloquy that begins with "To be, or not to be" in the play "Hamlet"?', 'A. Hamlet', 'B. Macbeth', 'C. Romeo', 'D. Othello', 'A'),
(19, 'Who is the author of the play "Othello"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(19, 'Which of Shakespeare\'s plays is set in the city of Venice?', 'A. Othello', 'B. Romeo and Juliet', 'C. Macbeth', 'D. Hamlet', 'A'),
(19, 'What is the name of the character who gives the famous "Friends, Romans, countrymen" speech in the play "Julius Caesar"?', 'A. Mark Antony', 'B. Brutus', 'C. Cassius', 'D. Caesar', 'A'),
(19, 'What is the name of the fairy king in the play "A Midsummer Night\'s Dream"?', 'A. Oberon', 'B. Puck', 'C. Titania', 'D. Romeo', 'A'),
(19, 'Which play features the character of Viola disguised as a man named Cesario?', 'A. Twelfth Night', 'B. The Tempest', 'C. King Lear', 'D. Much Ado About Nothing', 'A'),
(19, 'In which play does the character Lady Macbeth famously say, "Out, damned spot! Out, I say!"?', 'A. Macbeth', 'B. Hamlet', 'C. Romeo and Juliet', 'D. Othello', 'A'),
(19, 'What is the name of the character who delivers the "All the world\'s a stage" monologue in the play "As You Like It"?', 'A. Jaques', 'B. Rosalind', 'C. Orlando', 'D. Viola', 'A'),
-- midterm for TestID: 7 (Shakespearean Literature)
(20, 'Who is the author of the play "Romeo and Juliet"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(20, 'In which city is the play "Macbeth" primarily set?', 'A. Inverness', 'B. Rome', 'C. Athens', 'D. Verona', 'A'),
(20, 'What is the name of the character known for his famous soliloquy that begins with "To be, or not to be" in the play "Hamlet"?', 'A. Hamlet', 'B. Macbeth', 'C. Romeo', 'D. Othello', 'A'),
(20, 'Who is the author of the play "Othello"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(20, 'Which of Shakespeare\'s plays is set in the city of Venice?', 'A. Othello', 'B. Romeo and Juliet', 'C. Macbeth', 'D. Hamlet', 'A'),
(20, 'What is the name of the character who gives the famous "Friends, Romans, countrymen" speech in the play "Julius Caesar"?', 'A. Mark Antony', 'B. Brutus', 'C. Cassius', 'D. Caesar', 'A'),
(20, 'What is the name of the fairy king in the play "A Midsummer Night\'s Dream"?', 'A. Oberon', 'B. Puck', 'C. Titania', 'D. Romeo', 'A'),
(20, 'Which play features the character of Viola disguised as a man named Cesario?', 'A. Twelfth Night', 'B. The Tempest', 'C. King Lear', 'D. Much Ado About Nothing', 'A'),
(20, 'In which play does the character Lady Macbeth famously say, "Out, damned spot! Out, I say!"?', 'A. Macbeth', 'B. Hamlet', 'C. Romeo and Juliet', 'D. Othello', 'A'),
(20, 'What is the name of the character who delivers the "All the world\'s a stage" monologue in the play "As You Like It"?', 'A. Jaques', 'B. Rosalind', 'C. Orlando', 'D. Viola', 'A'),
-- final for TestID: 7 (Shakespearean Literature)
(21, 'Who is the author of the play "Romeo and Juliet"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(21, 'In which city is the play "Macbeth" primarily set?', 'A. Inverness', 'B. Rome', 'C. Athens', 'D. Verona', 'A'),
(21, 'What is the name of the character known for his famous soliloquy that begins with "To be, or not to be" in the play "Hamlet"?', 'A. Hamlet', 'B. Macbeth', 'C. Romeo', 'D. Othello', 'A'),
(21, 'Who is the author of the play "Othello"?', 'A. William Shakespeare', 'B. John Milton', 'C. Geoffrey Chaucer', 'D. Charles Dickens', 'A'),
(21, 'Which of Shakespeare\'s plays is set in the city of Venice?', 'A. Othello', 'B. Romeo and Juliet', 'C. Macbeth', 'D. Hamlet', 'A'),
(21, 'What is the name of the character who gives the famous "Friends, Romans, countrymen" speech in the play "Julius Caesar"?', 'A. Mark Antony', 'B. Brutus', 'C. Cassius', 'D. Caesar', 'A'),
(21, 'What is the name of the fairy king in the play "A Midsummer Night\'s Dream"?', 'A. Oberon', 'B. Puck', 'C. Titania', 'D. Romeo', 'A'),
(21, 'Which play features the character of Viola disguised as a man named Cesario?', 'A. Twelfth Night', 'B. The Tempest', 'C. King Lear', 'D. Much Ado About Nothing', 'A'),
(21, 'In which play does the character Lady Macbeth famously say, "Out, damned spot! Out, I say!"?', 'A. Macbeth', 'B. Hamlet', 'C. Romeo and Juliet', 'D. Othello', 'A'),
(21, 'What is the name of the character who delivers the "All the world\'s a stage" monologue in the play "As You Like It"?', 'A. Jaques', 'B. Rosalind', 'C. Orlando', 'D. Viola', 'A'),
-- quiz for TestID: 8 (Modern Poetry)
(22, 'Who is the author of the poem "The Waste Land"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(22, 'Which poet is associated with the Harlem Renaissance?', 'A. Langston Hughes', 'B. Maya Angelou', 'C. Robert Frost', 'D. Sylvia Plath', 'A'),
(22, 'What is the title of Robert Frost\'s famous poem that begins with "Two roads diverged in a yellow wood"?', 'A. The Road Not Taken', 'B. Stopping by Woods on a Snowy Evening', 'C. Fire and Ice', 'D. The Love Song of J. Alfred Prufrock', 'A'),
(22, 'Who is the author of the poem "The Love Song of J. Alfred Prufrock"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(22, 'What is the title of Langston Hughes\'s famous poem that asks the question "What happens to a dream deferred?"', 'A. Harlem', 'B. Dreams', 'C. I, Too', 'D. A Dream Deferred', 'D'),
(22, 'Which poet is known for her unconventional use of capitalization and punctuation?', 'A. e.e. cummings', 'B. Sylvia Plath', 'C. Maya Angelou', 'D. Emily Dickinson', 'A'),
(22, 'What is the title of Maya Angelou\'s autobiography that explores themes of identity and racism?', 'A. I Know Why the Caged Bird Sings', 'B. The Bell Jar', 'C. The Color Purple', 'D. Beloved', 'A'),
(22, 'Which poet wrote the famous line "Because I could not stop for Death, He kindly stopped for me"?', 'A. Emily Dickinson', 'B. T.S. Eliot', 'C. Langston Hughes', 'D. Robert Frost', 'A'),
(22, 'What is the title of Sylvia Plath\'s only novel?', 'A. The Bell Jar', 'B. The Waste Land', 'C. The Catcher in the Rye', 'D. To Kill a Mockingbird', 'A'),
(22, 'Which poet is known for her powerful performances and activism?', 'A. Maya Angelou', 'B. Emily Dickinson', 'C. Sylvia Plath', 'D. Langston Hughes', 'A'),
-- midterm for TestID: 8 (Modern Poetry)
(23, 'Who is the author of the poem "The Waste Land"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(23, 'Which poet is associated with the Harlem Renaissance?', 'A. Langston Hughes', 'B. Maya Angelou', 'C. Robert Frost', 'D. Sylvia Plath', 'A'),
(23, 'What is the title of Robert Frost\'s famous poem that begins with "Two roads diverged in a yellow wood"?', 'A. The Road Not Taken', 'B. Stopping by Woods on a Snowy Evening', 'C. Fire and Ice', 'D. The Love Song of J. Alfred Prufrock', 'A'),
(23, 'Who is the author of the poem "The Love Song of J. Alfred Prufrock"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(23, 'What is the title of Langston Hughes\'s famous poem that asks the question "What happens to a dream deferred?"', 'A. Harlem', 'B. Dreams', 'C. I, Too', 'D. A Dream Deferred', 'D'),
(23, 'Which poet is known for her unconventional use of capitalization and punctuation?', 'A. e.e. cummings', 'B. Sylvia Plath', 'C. Maya Angelou', 'D. Emily Dickinson', 'A'),
(23, 'What is the title of Maya Angelou\'s autobiography that explores themes of identity and racism?', 'A. I Know Why the Caged Bird Sings', 'B. The Bell Jar', 'C. The Color Purple', 'D. Beloved', 'A'),
(23, 'Which poet wrote the famous line "Because I could not stop for Death, He kindly stopped for me"?', 'A. Emily Dickinson', 'B. T.S. Eliot', 'C. Langston Hughes', 'D. Robert Frost', 'A'),
(23, 'What is the title of Sylvia Plath\'s only novel?', 'A. The Bell Jar', 'B. The Waste Land', 'C. The Catcher in the Rye', 'D. To Kill a Mockingbird', 'A'),
(23, 'Which poet is known for her powerful performances and activism?', 'A. Maya Angelou', 'B. Emily Dickinson', 'C. Sylvia Plath', 'D. Langston Hughes', 'A'),
-- final for TestID: 8 (Modern Poetry)
(24, 'Who is the author of the poem "The Waste Land"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(24, 'Which poet is associated with the Harlem Renaissance?', 'A. Langston Hughes', 'B. Maya Angelou', 'C. Robert Frost', 'D. Sylvia Plath', 'A'),
(24, 'What is the title of Robert Frost\'s famous poem that begins with "Two roads diverged in a yellow wood"?', 'A. The Road Not Taken', 'B. Stopping by Woods on a Snowy Evening', 'C. Fire and Ice', 'D. The Love Song of J. Alfred Prufrock', 'A'),
(24, 'Who is the author of the poem "The Love Song of J. Alfred Prufrock"?', 'A. T.S. Eliot', 'B. Robert Frost', 'C. Emily Dickinson', 'D. Langston Hughes', 'A'),
(24, 'What is the title of Langston Hughes\'s famous poem that asks the question "What happens to a dream deferred?"', 'A. Harlem', 'B. Dreams', 'C. I, Too', 'D. A Dream Deferred', 'D'),
(24, 'Which poet is known for her unconventional use of capitalization and punctuation?', 'A. e.e. cummings', 'B. Sylvia Plath', 'C. Maya Angelou', 'D. Emily Dickinson', 'A'),
(24, 'What is the title of Maya Angelou\'s autobiography that explores themes of identity and racism?', 'A. I Know Why the Caged Bird Sings', 'B. The Bell Jar', 'C. The Color Purple', 'D. Beloved', 'A'),
(24, 'Which poet wrote the famous line "Because I could not stop for Death, He kindly stopped for me"?', 'A. Emily Dickinson', 'B. T.S. Eliot', 'C. Langston Hughes', 'D. Robert Frost', 'A'),
(24, 'What is the title of Sylvia Plath\'s only novel?', 'A. The Bell Jar', 'B. The Waste Land', 'C. The Catcher in the Rye', 'D. To Kill a Mockingbird', 'A'),
(24, 'Which poet is known for her powerful performances and activism?', 'A. Maya Angelou', 'B. Emily Dickinson', 'C. Sylvia Plath', 'D. Langston Hughes', 'A'),
-- Quiz for TestID: 9 (Painting Techniques)
(25, 'Which painting technique involves applying thin layers of translucent paint to create depth and luminosity?', 'A. Glazing', 'B. Impasto', 'C. Sgraffito', 'D. Scumbling', 'A'),
(25, 'Which artist is known for his use of pointillism, a technique that involves using small dots of color to create an image?', 'A. Georges Seurat', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Leonardo da Vinci', 'A'),
(25, 'What is the term for a painting technique that involves building up thick layers of paint on the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(25, 'Which painting technique involves scraping or scratching the surface of a painting to reveal underlying layers?', 'A. Sgraffito', 'B. Impasto', 'C. Glazing', 'D. Scumbling', 'A'),
(25, 'Who is the artist known for his use of perspective and realistic representation in his paintings?', 'A. Leonardo da Vinci', 'B. Salvador Dalí', 'C. Frida Kahlo', 'D. Jackson Pollock', 'A'),
(25, 'Which painting technique involves using broad, sweeping brushstrokes to create movement and energy in a painting?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(25, 'What is the term for a painting technique that involves applying wet paint onto wet paint, allowing the colors to mix and blend together?', 'A. Wet-on-wet', 'B. Drybrush', 'C. Wet-on-dry', 'D. Tonalism', 'A'),
(25, 'Which artist is known for his use of light and shadow, particularly in his portraits?', 'A. Rembrandt', 'B. Andy Warhol', 'C. Jackson Pollock', 'D. Claude Monet', 'A'),
(25, 'What is the term for a painting technique that involves creating texture by applying thick, textured paint to the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(25, 'Who is the artist known for his bold, abstract paintings and his drip painting technique?', 'A. Jackson Pollock', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Henri Matisse', 'A'),
-- midterm for TestID: 9 (Painting Techniques)
(26, 'Which painting technique involves applying thin layers of translucent paint to create depth and luminosity?', 'A. Glazing', 'B. Impasto', 'C. Sgraffito', 'D. Scumbling', 'A'),
(26, 'Which artist is known for his use of pointillism, a technique that involves using small dots of color to create an image?', 'A. Georges Seurat', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Leonardo da Vinci', 'A'),
(26, 'What is the term for a painting technique that involves building up thick layers of paint on the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(26, 'Which painting technique involves scraping or scratching the surface of a painting to reveal underlying layers?', 'A. Sgraffito', 'B. Impasto', 'C. Glazing', 'D. Scumbling', 'A'),
(26, 'Who is the artist known for his use of perspective and realistic representation in his paintings?', 'A. Leonardo da Vinci', 'B. Salvador Dalí', 'C. Frida Kahlo', 'D. Jackson Pollock', 'A'),
(26, 'Which painting technique involves using broad, sweeping brushstrokes to create movement and energy in a painting?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(26, 'What is the term for a painting technique that involves applying wet paint onto wet paint, allowing the colors to mix and blend together?', 'A. Wet-on-wet', 'B. Drybrush', 'C. Wet-on-dry', 'D. Tonalism', 'A'),
(26, 'Which artist is known for his use of light and shadow, particularly in his portraits?', 'A. Rembrandt', 'B. Andy Warhol', 'C. Jackson Pollock', 'D. Claude Monet', 'A'),
(26, 'What is the term for a painting technique that involves creating texture by applying thick, textured paint to the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(26, 'Who is the artist known for his bold, abstract paintings and his drip painting technique?', 'A. Jackson Pollock', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Henri Matisse', 'A'),
-- final for TestID: 9 (Painting Techniques)
(27, 'Which painting technique involves applying thin layers of translucent paint to create depth and luminosity?', 'A. Glazing', 'B. Impasto', 'C. Sgraffito', 'D. Scumbling', 'A'),
(27, 'Which artist is known for his use of pointillism, a technique that involves using small dots of color to create an image?', 'A. Georges Seurat', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Leonardo da Vinci', 'A'),
(27, 'What is the term for a painting technique that involves building up thick layers of paint on the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(27, 'Which painting technique involves scraping or scratching the surface of a painting to reveal underlying layers?', 'A. Sgraffito', 'B. Impasto', 'C. Glazing', 'D. Scumbling', 'A'),
(27, 'Who is the artist known for his use of perspective and realistic representation in his paintings?', 'A. Leonardo da Vinci', 'B. Salvador Dalí', 'C. Frida Kahlo', 'D. Jackson Pollock', 'A'),
(27, 'Which painting technique involves using broad, sweeping brushstrokes to create movement and energy in a painting?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(27, 'What is the term for a painting technique that involves applying wet paint onto wet paint, allowing the colors to mix and blend together?', 'A. Wet-on-wet', 'B. Drybrush', 'C. Wet-on-dry', 'D. Tonalism', 'A'),
(27, 'Which artist is known for his use of light and shadow, particularly in his portraits?', 'A. Rembrandt', 'B. Andy Warhol', 'C. Jackson Pollock', 'D. Claude Monet', 'A'),
(27, 'What is the term for a painting technique that involves creating texture by applying thick, textured paint to the canvas?', 'A. Impasto', 'B. Glazing', 'C. Sgraffito', 'D. Scumbling', 'A'),
(27, 'Who is the artist known for his bold, abstract paintings and his drip painting technique?', 'A. Jackson Pollock', 'B. Pablo Picasso', 'C. Vincent van Gogh', 'D. Henri Matisse', 'A'),
-- quiz for TestID: 10 (Sculpture I)
(28, 'What is the term for a sculpture that is meant to be viewed from all angles?', 'A. Freestanding', 'B. Relief', 'C. Bas-relief', 'D. Kinetic', 'A'),
(28, 'Which artist is known for his bronze sculptures, including "The Thinker" and "The Kiss"?', 'A. Auguste Rodin', 'B. Michelangelo', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(28, 'What is the term for a sculpture technique that involves shaping a pliable material, such as clay or wax?', 'A. Modeling', 'B. Carving', 'C. Casting', 'D. Assembling', 'A'),
(28, 'Which ancient civilization is known for its monumental stone sculptures, such as the Great Sphinx and the statues of Ramses II?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(28, 'What is the term for a sculpture technique that involves cutting away material from a solid block to create a form?', 'A. Carving', 'B. Modeling', 'C. Casting', 'D. Assembling', 'A'),
(28, 'Who is the artist known for his mobile sculptures, which are balanced and move with the air currents?', 'A. Alexander Calder', 'B. Auguste Rodin', 'C. Michelangelo', 'D. Pablo Picasso', 'A'),
(28, 'Which ancient civilization is known for its terracotta army, a collection of life-sized sculptures representing warriors and horses?', 'A. Ancient Chinese', 'B. Ancient Egyptians', 'C. Ancient Greeks', 'D. Ancient Romans', 'A'),
(28, 'What is the term for a sculpture technique that involves pouring liquid material into a mold and allowing it to harden?', 'A. Casting', 'B. Carving', 'C. Modeling', 'D. Assembling', 'A'),
(28, 'Who is the artist known for his sculpture "David," a masterpiece of Renaissance art?', 'A. Michelangelo', 'B. Auguste Rodin', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(28, 'What is the term for a sculpture that is attached to a wall or other surface and does not project forward?', 'A. Relief', 'B. Freestanding', 'C. Bas-relief', 'D. Kinetic', 'A'),
-- midterm for TestID: 10 (Sculpture I)
(29, 'What is the term for a sculpture that is meant to be viewed from all angles?', 'A. Freestanding', 'B. Relief', 'C. Bas-relief', 'D. Kinetic', 'A'),
(29, 'Which artist is known for his bronze sculptures, including "The Thinker" and "The Kiss"?', 'A. Auguste Rodin', 'B. Michelangelo', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(29, 'What is the term for a sculpture technique that involves shaping a pliable material, such as clay or wax?', 'A. Modeling', 'B. Carving', 'C. Casting', 'D. Assembling', 'A'),
(29, 'Which ancient civilization is known for its monumental stone sculptures, such as the Great Sphinx and the statues of Ramses II?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(29, 'What is the term for a sculpture technique that involves cutting away material from a solid block to create a form?', 'A. Carving', 'B. Modeling', 'C. Casting', 'D. Assembling', 'A'),
(29, 'Who is the artist known for his mobile sculptures, which are balanced and move with the air currents?', 'A. Alexander Calder', 'B. Auguste Rodin', 'C. Michelangelo', 'D. Pablo Picasso', 'A'),
(29, 'Which ancient civilization is known for its terracotta army, a collection of life-sized sculptures representing warriors and horses?', 'A. Ancient Chinese', 'B. Ancient Egyptians', 'C. Ancient Greeks', 'D. Ancient Romans', 'A'),
(29, 'What is the term for a sculpture technique that involves pouring liquid material into a mold and allowing it to harden?', 'A. Casting', 'B. Carving', 'C. Modeling', 'D. Assembling', 'A'),
(29, 'Who is the artist known for his sculpture "David," a masterpiece of Renaissance art?', 'A. Michelangelo', 'B. Auguste Rodin', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(29, 'What is the term for a sculpture that is attached to a wall or other surface and does not project forward?', 'A. Relief', 'B. Freestanding', 'C. Bas-relief', 'D. Kinetic', 'A'),
-- final for TestID: 10 (Sculpture I)
(30, 'What is the term for a sculpture that is meant to be viewed from all angles?', 'A. Freestanding', 'B. Relief', 'C. Bas-relief', 'D. Kinetic', 'A'),
(30, 'Which artist is known for his bronze sculptures, including "The Thinker" and "The Kiss"?', 'A. Auguste Rodin', 'B. Michelangelo', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(30, 'What is the term for a sculpture technique that involves shaping a pliable material, such as clay or wax?', 'A. Modeling', 'B. Carving', 'C. Casting', 'D. Assembling', 'A'),
(30, 'Which ancient civilization is known for its monumental stone sculptures, such as the Great Sphinx and the statues of Ramses II?', 'A. Ancient Egyptians', 'B. Ancient Greeks', 'C. Ancient Romans', 'D. Ancient Persians', 'A'),
(30, 'What is the term for a sculpture technique that involves cutting away material from a solid block to create a form?', 'A. Carving', 'B. Modeling', 'C. Casting', 'D. Assembling', 'A'),
(30, 'Who is the artist known for his mobile sculptures, which are balanced and move with the air currents?', 'A. Alexander Calder', 'B. Auguste Rodin', 'C. Michelangelo', 'D. Pablo Picasso', 'A'),
(30, 'Which ancient civilization is known for its terracotta army, a collection of life-sized sculptures representing warriors and horses?', 'A. Ancient Chinese', 'B. Ancient Egyptians', 'C. Ancient Greeks', 'D. Ancient Romans', 'A'),
(30, 'What is the term for a sculpture technique that involves pouring liquid material into a mold and allowing it to harden?', 'A. Casting', 'B. Carving', 'C. Modeling', 'D. Assembling', 'A'),
(30, 'Who is the artist known for his sculpture "David," a masterpiece of Renaissance art?', 'A. Michelangelo', 'B. Auguste Rodin', 'C. Pablo Picasso', 'D. Alexander Calder', 'A'),
(30, 'What is the term for a sculpture that is attached to a wall or other surface and does not project forward?', 'A. Relief', 'B. Freestanding', 'C. Bas-relief', 'D. Kinetic', 'A');




